### ISSUE TITLE
Cell 1 has an issue importing sciits.samplerate

### ISSUE THREAD

**Issue by ToddG** [amsehili/audio-segmentation-by-classification-tutorial#2]
Cell 1 has an issue importing sciits.samplerate:

```python
import wave
import pickle
import numpy as np
from sklearn.mixture import GMM
import librosa
from auditok import DataValidator, ADSFactory, DataSource, StreamTokenizer, BufferAudioSource, player_for
```

```bash
/home/todd/bin/anaconda3/envs/audio/lib/python3.5/site-packages/librosa/core/audio.py:37: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
  warnings.warn('Could not import scikits.samplerate. '
```

**Comment by amsehili** [comment]
This is because `librosa` first looks for `scikits.samplerate` (used for audio re-sampling) before it falls back to `scipy`. This is an ugly, though harmless warning. You can get rid of it by adding the following instructions before `import librosa`:

    import warnings
    warnings.filterwarnings('ignore', '.*scikits.*')

I don't think it's a good idea to add them to the cell however. We can tell the user not to pay attention to the warning anyway.
